FROM node:20-alpine AS base

WORKDIR /app

FROM base AS deps
COPY frontend/package*.json ./
RUN npm ci

FROM base AS dev
COPY --from=deps /app/node_modules ./node_modules
COPY frontend/ .

EXPOSE 3000

CMD ["npm", "run", "dev"]
