"""initial schema

Revision ID: da934eca16fd
Revises: 
Create Date: 2026-07-04 00:12:09.276189

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'da934eca16fd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agents_organization_id', 'agents', ['organization_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'channel_type', 'organization_id', name='uq_contacts_external_id_channel_org')
    )
    op.create_index('ix_contacts_organization_id', 'contacts', ['organization_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    op.create_index('ix_conversations_opportunity_id', 'conversations', ['opportunity_id'], unique=False)
    op.create_table('internal_users',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_internal_users_organization_id', 'internal_users', ['organization_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('conversation_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('sender_role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_sent_at', 'messages', ['sent_at'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('contact_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('agent_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('assigned_advisor_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attention_mode', sa.String(length=50), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunities_contact_id', 'opportunities', ['contact_id'], unique=False)
    op.create_index('ix_opportunities_organization_id', 'opportunities', ['organization_id'], unique=False)
    op.create_index('ix_opportunities_status', 'opportunities', ['status'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_opportunities_status', table_name='opportunities')
    op.drop_index('ix_opportunities_organization_id', table_name='opportunities')
    op.drop_index('ix_opportunities_contact_id', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index('ix_messages_sent_at', table_name='messages')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_internal_users_organization_id', table_name='internal_users')
    op.drop_table('internal_users')
    op.drop_index('ix_conversations_opportunity_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_contacts_organization_id', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_agents_organization_id', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
